name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Restore dependencies
      run: dotnet restore webapiconcesionario.sln

    - name: Build
      run: dotnet build webapiconcesionario.sln --configuration Release --no-restore
